version: '3.8'

services:

  web:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/fastapi_sqlmodel
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin@db:5432/fastapi_sqlmodel_db
    depends_on:
      - db

  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastapi_sqlmodel_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  postgres_data: